### ISSUE TITLE
(WIN32)error WinSock.h has already been included- fixed

### ISSUE THREAD

**Issue by hexxcointakeover** [SCDeveloper/DarkSilk-Release-Candidate#170]
tested to compile with win32/mingw, without i2p.
removes the error.
have no time to make pull requests now.

rpcprotocol.h current code:

#ifndef DARKSILKRPC_PROTOCOL_H
#define DARKSILKRPC_PROTOCOL_H

#include <boost/iostreams/concepts.hpp
#include <boost/iostreams/stream.hpp
#include <boost/asio.hpp
#include <boost/asio/ssl.hpp

#include <list
#include <map
#include <stdint.h
#include <string

#include "json/json_spirit_reader_template.h"
#include "json/json_spirit_utils.h"
#include "json/json_spirit_writer_template.h"

#include "compat/compat.h"

-------------------------------------------------

the fix:

#ifndef DARKSILKRPC_PROTOCOL_H
#define DARKSILKRPC_PROTOCOL_H

#include "compat/compat.h"
#include <list
#include <map
#include <stdint.h
#include <string
#include <boost/iostreams/concepts.hpp
#include <boost/iostreams/stream.hpp
#include <boost/asio.hpp
#include <boost/asio/ssl.hpp

#include "json/json_spirit_reader_template.h"
#include "json/json_spirit_utils.h"
#include "json/json_spirit_writer_template.h"

----------------
some marks removed from end of most lines because some forum problem!!!

**Comment by SCDeveloper** [comment]
WIll create a branch called WinSock and push my changes there. Will wait on Cisahasa to then test and will merge based on the success of his Windows build.

**Comment by SCDeveloper** [comment]
https://github.com/SCDeveloper/DarkSilk-Release-Candidate/commit/4d3f764aa9f05944a61a8488390a1d70b2ec67a1

Potential Fix

**Comment by hexxcointakeover** [comment]
not tested yet.
yes, there is also an issue with ip2sam files, this maybe for it.
(you got that as PM)

but the latest error i posted was compiled with i2p totally removed from the whole code.

**Comment by SCDeveloper** [comment]
Ah ok, well ive merged the include changes as that just needed doing anyway. I will investigate further.

**Comment by SCDeveloper** [comment]
Commited a change to WinSock and merged with Main. Please test hexxcointakeover ;)

**Comment by SCDeveloper** [comment]
https://github.com/SCDeveloper/DarkSilk-Release-Candidate/commit/b4deaaa2fffc956fe5300f2a34515fa7af075188

**Comment by hexxcointakeover** [comment]
still wont compile

**Comment by hexxcointakeover** [comment]
i got tired of that error and skipped it by changing error to warning to boost:socket_types.hpp.
"#  warning WinSock.h has already been included"
compiles and downloads blocks..

this should not be the solution...

**Comment by hexxcointakeover** [comment]
solved, testing to be done.

**Comment by hexxcointakeover** [comment]
fixed
