### ISSUE TITLE
pow2argon -- CreateTransaction(): ERROR: Signing transaction failed

### ISSUE THREAD

**Issue by GregoryBetz** [SCDeveloper/DarkSilk-Release-Candidate#193]
This is the error message in the debug.log when trying to send a transaction through the qt console.

**Comment by CryptoDJ** [comment]
What is the error message?

**Comment by hexxcointakeover** [comment]
corrupted wallet.dat? cant read privkey? rescan?

**Comment by GregoryBetz** [comment]
The error is in the title: 

CreateTransaction(): ERROR: Signing transaction failed

**Comment by GregoryBetz** [comment]
@hexxcointakeover I replicated the error with a fresh database a total of three times, so I don't think it is the wallet.dat, but I could be wrong. If it was something with the wallet.dat, I think the debug.log would be explicit about that file at least, right?

**Comment by hexxcointakeover** [comment]
most common reason for this error code is wallet.
i would try with new wallet and then check after code if script_error changes broked something.
sadly i do not have my linux currently up to test myself.

**Comment by GregoryBetz** [comment]
Here is the warning output that I think is causing this error:

src/txmempool.cpp: In member function 'bool CTxMemPool::addUnchecked(const uint256&, const CTxMemPoolEntry&)':
src/txmempool.cpp:106:59: warning: invalid conversion from 'const CTransaction*' to 'CTransaction*' [-fpermissive]
             mapNextTx[tx.vin[i].prevout] = CInPoint(&tx, i);
                                                           ^
In file included from src/script/compressor.h:9:0,
                 from src/undo.h:9,
                 from src/coins.h:16,
                 from src/txmempool.h:14,
                 from src/txmempool.cpp:7:
src/primitives/transaction.h:86:5: warning:   initializing argument 1 of 'CInPoint::CInPoint(CTransaction*, unsigned int)' [-fpermissive]
     CInPoint(CTransaction* ptxIn, unsigned int nIn) { ptx = ptxIn; n = nIn; }
     ^
src/txmempool.cpp: In member function 'void CTxMemPool::removeCoinbaseSpends(const CCoinsViewCache*, unsigned int)':
src/txmempool.cpp:272:85: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (!coins || (coins->IsCoinBase() && nMemPoolHeight - coins->nHeight < nCoinbaseMaturity)) {
                                                                                     ^

**Comment by hexxcointakeover** [comment]
this one i posted to spencer days ago:

src\txmempool.cpp: In member function 'void CTxMemPool::removeCoinbaseSpends(const CCoinsViewCache*, unsigned int)':
src\txmempool.cpp:272:83: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (!coins || (coins->IsCoinBase() && nMemPoolHeight - coins->nHeight < nCoinbaseMaturity)) {

**Comment by GregoryBetz** [comment]
Resolved by https://github.com/SCDeveloper/DarkSilk-Release-Candidate/pull/197
