### ISSUE TITLE
Fix CNodeStats.dPingTime.  All = zero (0).

### ISSUE THREAD

**Issue by CryptoDJ** [SCDeveloper/DarkSilk-Release-Candidate#37]
Currently dPingTime = 0 for all peers.  Also check sync height, and nMisbehavior.

**Comment by SCDeveloper** [comment]
CStormnode:Broadcast is being added along with Snping and other functions.

**Comment by CryptoDJ** [comment]
Fixed by removing BIP0031_VERSION
