### ISSUE TITLE
Split Transaction for PoS

### ISSUE THREAD

**Issue by CryptoDJ** [SCDeveloper/DarkSilk-Release-Candidate#43]
PoS transaction rewards are split into two and the second output is zero.  Does not happen for every block reward.

**Comment by SCDeveloper** [comment]
Will be increasing split size to 100 and static PoS reward to 4 and we can retest.

**Comment by SCDeveloper** [comment]
https://github.com/SCDeveloper/DarkSilk-Release-Candidate/commit/3d59fe3da050f04f32a415bec4d9d969629d889e

**Comment by SCDeveloper** [comment]
I believe this is no longer an issue :dancer:
