### ISSUE TITLE
Coincontrol UI issue with checked items persisting when gone bug.

### ISSUE THREAD

**Issue by CryptoDJ** [SCDeveloper/DarkSilk-Release-Candidate#89]
Steps to reproduce this bug:
1) select all inputs in coincontrol. 
2) close coincontrol.  
3) wait until you get a PoS reward.  
4) open coincontrol
5) those selected inputs are stuck and  can't be unselect without restarting the wallet.

**Comment by SCDeveloper** [comment]
https://github.com/SCDeveloper/DarkSilk-Release-Candidate/commit/8c2e4939719f0416764713cdcf353a9ec10f9a0b
